Add DQL support
atom/language-php pull request #448
Opened 2022-01-20 09:34 UTC by eexit

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Hello,

This tiny PR adds support for [Doctrine Query Language](https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/dql-doctrine-query-language.html) syntax coloration in heredocs.

Example:

![dql-support](https://user-images.githubusercontent.com/57098/150189952-78e6d5b6-b068-4772-8740-5f08b9be7c54.png)

Thanks!

### Alternate Designs

### Benefits

### Possible Drawbacks

### Applicable Issues

2022-01-20 10:27 UTC, KapitanOczywisty requested changes

2022-01-20 10:27 UTC, KapitanOczywisty commented on grammars/php.cson
> +        'begin': '(<<<)\\s*("?)((D|S)QL)(\\2)(\\s*)$'
```suggestion
        'begin': '(<<<)\\s*("?)([DS]QL)(\\2)(\\s*)$'
```

2022-01-20 10:27 UTC, KapitanOczywisty commented on grammars/php.cson
> +        'begin': '(<<<)\\s*\'((D|S)QL)\'(\\s*)$'
```suggestion
        'begin': '(<<<)\\s*\'([DS]QL)\'(\\s*)$'
```

2022-01-20 11:58 UTC, KapitanOczywisty approved these changes
Looks good! 👍

2022-02-15 19:39 UTC, KapitanOczywisty commented
Merging PRs takes a while here.

2022-05-20 09:38 UTC, eexit commented
Hello, any update? It's been 5 months now 🙃

2022-05-20 10:24 UTC, KapitanOczywisty commented
I told you :) @darangi @sadick254 any chance to merge some PRs? This and #456

2022-05-20 10:27 UTC, darangi commented
@KapitanOczywisty @eexit Will take a look at the PRs

2022-05-20 10:33 UTC, darangi commented
Thanks for the contribution 🙇🏾  @eexit

2022-05-20 10:34 UTC, merged

2022-05-20 10:47 UTC, eexit commented
Anytime!

2022-07-07 09:41 UTC, eexit commented
Hey @darangi, will you plan to ever release the latest merges? Latest release is from Jan 17th...